name: Automated Quality Gate

on:
    workflow_dispatch:
    pull_request:
        types: [labeled]
        branches: [main]

jobs:
    review:
        name: ReviewSource
        runs-on: ubuntu-latest
        if: ${{ github.event.label.name == 'review' }}
        steps:
            - name: Code Review
              uses: pragmatic-bear/sfdx-code-review-action@v0.5.2
              with:
                  pmdconfig: tech-debt-ruleset.xml
                  github_token: ${{ secrets.GITHUB_TOKEN }}
